server:
  port: 8765

spring:
  main:
    banner-mode: off
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

swagger:
  enabled: true

elasticsearch:
  host: localhost
  port: 9200
  connTimeout: 3000  # ???????????????
  socketTimeout: 5000  # ???????????????????
  connectionRequestTimeout: 500  # httpclient??????????????????????????????
